import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "../components/SideBar/Sidebar";
import { SideBarItem } from "@/components/SideBar/SideBarItem";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="flex min-h-screen">
          <SideBar>
            <SideBarItem text="Crear Producto" path="/create"></SideBarItem>
            <SideBarItem
              text="Ver Productos"
              path="/products"
            ></SideBarItem>
          </SideBar>
          
        {children}
        </main>
      </body>
    </html>
  );
}
